name: develop PR Test

on:
  pull_request:
    branches:
      - master
      - develop

jobs:
  junit_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 16
        uses: actions/setup-java@v1
        with:
          java-version: 16

      - name: compile test file
        run: javac -d out/test -cp ./lib/junit-platform-console-standalone-1.8.1.jar ./test/**/*.java

      - name: test junit
        run: java -jar ./lib/junit-platform-console-standalone-1.8.1.jar --class-path out/test --include-classname='.*'  --scan-class-path --reports-dir=out/test-results

      # 테스트 후 Result를 보기위해 Publish Unit Test Results step 추가
      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@v1
        if: ${{ always() }} # 테스트가 실패하여도 Report를 보기 위해 `always`로 설정
        with:
          files: out/test-results/**/*.xml

      - name: action-slack
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          author_name: Github Action Test # default: 8398a7@action-slack
          fields: repo,message,commit,author,action,eventName,ref,workflow,job,took
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }} # required
        if: always() # Pick up events even if the job fails or is canceled.
